### ISSUE TITLE
Some recipes giving incorrect output amounts

### ISSUE THREAD

**Issue by Gamemassa** [OffKilterMC/AutoCrafter#1]
Hi, not sure if this is an issue, but some recipes aren't giving me the proper output through the Craftomatic. One example is bone meal. Normally when you put a bone in a crafting table you get back 3 bonemeal, but I put a stack of bones through the Craftomatic and only got one stack of bone meal back when I should've got three. I'll fool around a bit and see if any other recipes are doing this.

Also, if it helps, I'm on 1.20.4 in an SP world. No idea if this bug also happens in MP servers because I don't actually have one to test with.

**Comment by OffKilterMC** [comment]
Thanks for the report! Based on the description, I have a feeling I know what is going wrong. Let me take a look and hopefully I can get a fix out today if I'm lucky.

**Comment by Gamemassa** [comment]
Update: I've noticed a pattern. It seems like if I put in an item with an input-to-output ratio of less than 1, the Craftomatic just gives me back one of the item I was supposed to get. Some examples are:

- An input of 1 bone should have an output of 3 bone meal
- An input of 1 gem or ore block (e.g. Diamond, Iron, etc.) should yield 9 gems/ingots

**Comment by OffKilterMC** [comment]
One question, are you using the passive or dropper variant for your examples here?

**Comment by Gamemassa** [comment]
> Thanks for the report! Based on the description, I have a feeling I know what is going wrong. Let me take a look and hopefully I can get a fix out today if I'm lucky.

No rush! Take your time. I'm sure Craftomatic's code is more complicated than it looks.

**Comment by Gamemassa** [comment]
> One question, are you using the passive or dropper variant for your examples here?

I'm using the Passive one right now. Would you like me to test the dropper one too?

**Comment by Gamemassa** [comment]
> One question, are you using the passive or dropper variant for your examples here?

~Ok, so I just tried the Dropper variant, and I'm not actually sure how to make that one do anything. The hopper above put the items into the Dropper Craftomatic, but the Cratomatic didn't seem to output anything to the hopper below or drop anything out the front. Then I looked in the Craftomatic and saw that it's displaying the output on the right where it's supposed to, but when I click on the output nothing happens.~

Please disregard this. I forgot I needed a redstone signal to turn it on.

**Comment by Gamemassa** [comment]
> One question, are you using the passive or dropper variant for your examples here?

Ok, so I just found two issues with the dropper version (both of which seem kinda serious):

1. It's having the same issue as I described above with the passive one, except it drops 2 of the output block instead of the correct amount.
2. It only seems to craft once and then I have to reset the redstone signal (e.g. replace the redstone torch or flip the lever on and off; not sure if this behavior is intended with the dropper version).

**Comment by OffKilterMC** [comment]
So I am looking at this right now and it's a bit tricky especially in the hopper variant. In a normal crafting table, you have to take all items out and when you do the input items are also removed. In this scenario, the hopper can only take out one item at a time. This mean I need to make a behavioral decision. For now I might make it make the ingredients disappear as soon as the first result is taken, and prevent new ingredients from being pulled in until the result is cleared.

Regarding the dropper behavior: yes, you need to reset each time. This matches actual dropper block behavior (and the upcoming vanilla crafter block last I checked). You would typically run it on a clock.

Oh, and I did also see the case where it spat out only two items as well. I'm looking at that at the same time...

**Comment by Gamemassa** [comment]
> So I am looking at this right now and it's a bit tricky especially in the hopper variant. In a normal crafting table, you have to take all items out and when you do the input items are also removed. In this scenario, the hopper can only take out one item at a time. This mean I need to make a behavioral decision. For now I might make it make the ingredients disappear as soon as the first result is taken, and prevent new ingredients from being pulled in until the result is cleared.
> 
> Regarding the dropper behavior: yes, you need to reset each time. This matches actual dropper block behavior (and the upcoming vanilla crafter block last I checked). You would typically run it on a clock.
> 
> Oh, and I did also see the case where it spat out only two items as well. I'm looking at that at the same time...

That actually sounds like a good idea on how to fix that issue. Also, I meant to say earlier, thanks so much for the quick reply!

**Comment by OffKilterMC** [comment]
I have (so far) fixed most of the issues. I am stuck on one last thing I ran into: in passive mode, if you place 16 honey bottles in the usual spot and let it craft, the glass bottles get lost (they have no place to go since the grid is still full of honey bottles). I am trying to find the best path for this. Either I will need to restrict placing items in the crafting grid when running in that mode, or I need to somehow just spew them out as the dropper would (but that seems... iffy). If you just use hoppers to input the items, everything runs fine. One other alternative is that if there is a template item in play, we restrict all crafting grid slots to a cap of item item per slot. That would also avoid the issue.

**Comment by OffKilterMC** [comment]
OK I've put a 1.0b2 up on Mondrith. I'm about to put it onto CurseForge but they are a bit slower and will need to approve it.

**Comment by Gamemassa** [comment]
Ok. I'm eating dinner right now, but I'll test 1.0b2 in a little bit.

**Comment by Gamemassa** [comment]
> OK I've put a 1.0b2 up on Mondrith. I'm about to put it onto CurseForge but they are a bit slower and will need to approve it.

Confirmed. The bugs above have been fixed in 1.0b2, except for one thing. In the dropper variant, am I supposed to be able to open the Craftomatic screen and click on the result box to retrieve the items, like with a normal crafting table? Because I can't do that currently, since nothing happens when I click on the result box.

**Comment by OffKilterMC** [comment]
I believe if you have something in the template slot, then the result slot is disabled. Glad to hear the rest is going better.

**Comment by Gamemassa** [comment]
> I believe if you have something in the template slot, then the result slot is disabled. Glad to hear the rest is going better.

Oh, ok. That makes sense.

**Comment by OffKilterMC** [comment]
Closing for now. If you see anything else, please let me know.
